version: '3.8'

services:
  app:
    image: node/food-api:v1
    ports:
      - 6464:6464
    env_file:
      - config.env
    # environment: # config in .env
    #   - REDIS_HOST=${REDIS_HOST}
    #   - REDIS_PORT=${REDIS_PORT}
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
