version: '3.8'

services:
  app:
    image: registry.gitlab.com/fresherduong/learning-docker:latest
    ports:
      - 6464:6464
    env_file:
      - config.env
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
